FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies including devDependencies
RUN npm install --force

# Copy configuration files
COPY postcss.config.mjs ./
COPY tailwind.config.js ./
COPY next.config.mjs ./

# Copy the rest of the application
COPY . .

EXPOSE 3000

# Use development mode
CMD ["npm", "run", "dev"]