version: "3.9"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
      MYSQL_DATABASE: bmtc
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
      MYSQL_DB: bmtc
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data: